### ISSUE TITLE
Prepare and test over a new dataset

### ISSUE THREAD

**Issue by modeorru** [NostrumBioDiscovery/modtox#14]
We should check the performances over an external dataset.

**Comment by danielSoler93** [comment]
Mode update this woth info abou what dataset did you us, how did you treat it and what are the first results please!

**Comment by modeorru** [comment]
The pipeline has been already tested with an external dataset from PubChem (with around 50 molecules). After converting the molecules to an standard system of identification, we've checked we were only using new molecules (to those used in the training process), so that the test was completely independent and the performances unbiased. We could finally predict with really good performances (only 1 mistaken molecule). During next days we should check the pipeline with a larger dataset.

**Comment by danielSoler93** [comment]
Pubchem test looks good. with the next results:

[MODTOX.pdf](https://github.com/NostrumBioDiscovery/modtox/files/3820624/MODTOX.pdf)

We close the issue and move the large dataset to another one.
