### ISSUE TITLE
Dude.py should be reviewed

### ISSUE THREAD

**Issue by modeorru** [NostrumBioDiscovery/modtox#15]
Dude.py script is a little messed up, so should be improved.

**Comment by danielSoler93** [comment]
I refactored the whole code, basically:

- Removed the database.py

- Create a single class DUDE that does not inherit from anyone

- Retrieve the inchis at dude_preprocess for you to write them out and compare train/test

Have a look and if you think is good enough close the issue.

Good laughs yesterday looking at the code (: haha
