### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by modeorru** [NostrumBioDiscovery/modtox#6]
We should improve installation : fix conflict between packages ?

**Comment by danielSoler93** [comment]
I updated **pypi** **installation**:

If you do the next should be easy installable:

1. conda create -n modtox_pip python=3.6
2. source activate modtox_pip
3. pip install modtox
4. conda install rdkit
5. python -m modtog.main -h

Can you give it a try if it works for you??

### Full conda installation is still being fixed

**Comment by modeorru** [comment]
Rdkit installation works to me with: "conda install -c rdkit rdkit". Step 5 gives me: "ImportError: dynamic module does not define module export function (PyInit_cpp_options)".

**Comment by danielSoler93** [comment]
I've checked it. This is because you have another pytraj installed and it's messing up path. Try this please:

1.     conda create -n modtox_pip2 python=3.6
2.     source activate modtox_pip2
3.     unset PYTHONPATH
4.     pip install modtox
5.     conda install -c rdkit rdkit
6.     python -m modtog.main -hx

**Comment by danielSoler93** [comment]
Please try all options here to check they work but first do: `unset PYTHONPATH`

https://nostrumbiodiscovery.github.io/modtox/installation/index.html

If they all work close the issue otherwise report please (:

Thanks

Dani

**Comment by modeorru** [comment]
I've tried the 3 installation procedures and worked almost perfectly: just the last two instructions for "From Source Code" should be executed in the reverse order (firstly install rdkit and then run the setup).

**Comment by NostrumBioDiscovery** [comment]
Perfect. Fixed on docs! Feel free to close issue if u agree

**Comment by NostrumBioDiscovery** [comment]
Changed on docs!
