### ISSUE TITLE
Problems with "parse" during the installation of modtox

### ISSUE THREAD

**Issue by modeorru** [NostrumBioDiscovery/modtox#7]
I got problems with the package "parse" since even though was installed couldn't run the program without getting "no module named parse". I think it has to be related with an incompatibility between python's versions (2.7 / 3). To solve this issue "manually", just rewrite few lines of different py-files in ../chembl_websource_client/ (e.g. replacing "from urllib.parse import urlparse" to "from urlparse import urlparse") so that could be executed with python2.7

**Comment by danielSoler93** [comment]
Same as issue #5 ?

**Comment by danielSoler93** [comment]
Duplicate of #5
